apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s --chart
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - env:
        - name: AUTH
          value: "yes"
        - name: MONGODB_ADMIN_PASS
        - name: MONGODB_ADMIN_USER
        - name: MONGODB_APPLICATION_DATABASE
        - name: MONGODB_APPLICATION_PASS
        - name: MONGODB_APPLICATION_USER
        image: aashreys/mongo-auth:latest
        name: docker-node-mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb
      restartPolicy: Always
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: mongodb
status: {}
